### PR TITLE
Remove reader conditional from cljs file

### LINKED ISSUE #1: Conditional read not allowed
It looks like you're using reader conditionals in a cljs file and it's failing during build:

```
[:app] Build failure:
------ ERROR -------------------------------------------------------------------
 File: jar:file:/home/winsome/.m2/repository/kee-frame-sockets/kee-frame-sockets/0.0.1/kee-frame-sockets-0.0.1.jar!/kee_frame/websocket.cljs:22:5
--------------------------------------------------------------------------------
  19 | 
  20 | 
  21 | (defn date []
  22 |   #?(:clj  (java.util.Date.)
-----------^--------------------------------------------------------------------
Conditional read not allowed

--------------------------------------------------------------------------------
  23 |      :cljs (js/Date.)))
  24 | 
  25 | (defn- receive-messages! [ws-chan {:keys [path dispatch]
  26 |                                    :as   socket-config}]
--------------------------------------------------------------------------------
```
I don't know if this is intended to work in a clj context, but if this is intended to be a clojurescript-only library we could just get rid of the `date` function and use the `js/Date constructor instead.

### PR DESCRIPTION
**Pull request by dpetranek**
Since we're already using unconditionaliaed js interop for the websocket url I just
removed the :clj conditional and inlined `js/Date` where necessary.

Fixes #1

### CODE REVIEW

**Comment by dpetranek** [comment]
It looks like the failed build has something to do with clojars credentials, which I don't think I can help with : )

**Comment by ingesolvoll** [comment]
@dpetranek 

Nice, thanks!

I don't often get to speak with users of this library, so if you have feedback or thoughts about it that would be interesting and helpful :)

**Comment by dpetranek** [comment]
No, thank you! I really like kee-frame!

I recommend it as the (correctly) opinionated way to start a re-frame project. So good job on having the correct opinions! :D

Once I get websockets working I'll probably add a section to the docs here about the backend.

**Comment by ingesolvoll** [comment]
@dpetranek Awesome, thanks :)

**Pull request merged**
